// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtWtpZ0qyTE-0Ox2cXNrwcMTBht0bN66o',
    appId: '1:225998234919:web:d955c148182e1a8cd77502',
    messagingSenderId: '225998234919',
    projectId: 'assignedproject-ea249',
    authDomain: 'assignedproject-ea249.firebaseapp.com',
    storageBucket: 'assignedproject-ea249.appspot.com',
    measurementId: 'G-MJCJ9RCC4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9MzPPvQtghYWTaNpW9EBM23ykvdVnikg',
    appId: '1:225998234919:android:b8461ad6651737afd77502',
    messagingSenderId: '225998234919',
    projectId: 'assignedproject-ea249',
    storageBucket: 'assignedproject-ea249.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKh8aG1hjPjOfsuJ9Fwkqk6Hid828C7aM',
    appId: '1:225998234919:ios:36824adba5e9d0fad77502',
    messagingSenderId: '225998234919',
    projectId: 'assignedproject-ea249',
    storageBucket: 'assignedproject-ea249.appspot.com',
    androidClientId: '225998234919-b33p0htfulguae0f5r8rn3j3sqm0t7d5.apps.googleusercontent.com',
    iosClientId: '225998234919-4eqbagp0g887l8ebj40tjiolrvbhabka.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
